Configuración Modelo Final

environment:
  python_version: '3.10.11'

preprocessing:
  image_size: [50, 50]
  color_mode: 'grayscale'
  histogram_equalization: true
  normalization: true

data:
  train_images_path: "data/processed/train/"
  test_images_path: "data/processed/test/"


augmentation:
  rotation_range: 20
  width_shift_range: 0.1
  height_shift_range: 0.1
  shear_range: 0.2
  zoom_range: 0.2
  horizontal_flip: true
  fill_mode: 'nearest'

model:
  type: Sequential
  layers:
    - Conv2D:
        filters: 32
        kernel_size: [3, 3]
        activation: 'relu'
        input_shape: [50, 50, 1]
    - MaxPooling2D:
        pool_size: [2, 2]
    - Conv2D:
        filters: 64
        kernel_size: [3, 3]
        activation: 'relu'
    - MaxPooling2D:
        pool_size: [2, 2]
    - Conv2D:
        filters: 128
        kernel_size: [3, 3]
        activation: 'relu'
    - Dropout:
        rate: 0.25
    - MaxPooling2D:
        pool_size: [2, 2]
    - Conv2D:
        filters: 64
        kernel_size: [3, 3]
        activation: 'relu'
    - MaxPooling2D:
        pool_size: [2, 2]
    - Flatten: {}
    - Dense:
        units: 50
        activation
